apiVersion: v1
kind: Service
metadata:
  name: front
  labels:
    run: front
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
      run: front
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: front
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: front
    spec:
      containers:
      - name: front
        image: otomato/oto-front:{{ .Values.global.frontVersion }}
        ports:
        - containerPort: 3000
